### ISSUE TITLE
Index overflow during isosurface

### ISSUE THREAD

**Issue by kephale** [bonej-org/BoneJ2#106]
https://github.com/bonej-org/BoneJ2/blob/9f24909be7c061ef8b64a69ef3e35ae2f2a4744b/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/IsosurfaceWrapper.java#L138

http://forum.imagej.net/t/bonej2-isosurface/11959/3

**Comment by rimadoma** [comment]
@dietzc Any insight into why `DefaultChunker` would throw an `ArrayIndexOutOfBoundsException` when converting a very large `Img` with [`ops.convert().bit(img)`](https://github.com/bonej-org/BoneJ2/blob/master/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java#L65)?

**Comment by ctrueden** [comment]
@rimadoma As I wrote [here](https://forum.image.sc/t/bonej2-isosurface/11959/10?u=ctrueden), we may want to add signatures to Ops that do the conversion lazily using the `Converters` utility class, instead of always pumping pixels upfront. In the meantime, have you tried calling `Converters.convert` to go from `T` to `BitType`?

**Comment by mdoube** [comment]
Fixed by https://github.com/imagej/imagej-ops/commit/badcaf6fe2906f0820da3d45e5f5385260bdc351
