### ISSUE TITLE
Connectivity is very slow

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#108]
Processing a 512×512×512 image on my 40-core workstation takes about 30 seconds instead of ~1 sec that the BoneJ1 version takes. BoneJ2 version needs multithreading - currently runs on one core.

**Comment by rimadoma** [comment]
Calling the algorithm through the Op framework creates some overhead, but certainly not the 30-fold increase seen here. It would be interesting to see if a larger image has similar magnitude of speed difference, or whether it evens out.

The parallellization of the code would have to go [here](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/topology/eulerCharacteristic/EulerCharacteristic26NFloating.java). I think it would be simpler to run the code inside the op in parallel rather than write the op so that several instances of it can be run at the same time. 

Connectivity is a memory bound problem, i.e. lots of quick accesses to shared RAM. My prediction is that you'll see gains from 2 to n (n << 40) cores, and then performance worsens again after n + 1 cores due parallellization overhead. 

Two parallellization strategies come to mind: either share a [RandomAccess](http://javadoc.scijava.org/ImgLib2/net/imglib2/RandomAccess.html), or process the image stack in sub-regions i.e. chunks. The former might be slow due having to synchronize access to the [RandomAccess], and the latter due cache misses.

Most other plug-ins are slower than in BoneJ1 as well. For me speed is not a top priority: it's more important that both plug-ins _A_ and _B_ work than _A_ works really fast. Also I feel that improving performance is somewhat premature on top of an API that is still changing. A project like this needs what I like to call _Kalashnikov code_: not the most sophisticated, but easy to maintain by anyone even in tough conditions.

**Comment by mdoube** [comment]
Experience shows that synchronising access is usually not the way to go - although my experience is limited to Java 6. Multithreading read-only access to ImageStack was straightforward because each slice lives in a separate array, so all you had to do was point each thread at its own slice. There was a natural chunking strategy. In IJ2, that might not be so clear, although if one is able to restrict an Op thread to work on only a single value of one of the dimensions, then you could easily avoid hitting values twice. This is a read-only process so there's no need to worry about values getting written and read out of sequence - main thing to do is allow the data to flow fast from memory to CPU.

While I agree that it's acceptable to have say a 10% performance hit due to more robust engineering, the current state of Connectivity is ~30× slower, making it a bit tedious for users who are used to the old code.

**Comment by rimadoma** [comment]
I've been toying around with Connectivity [here](https://github.com/imagej/imagej-ops/commits/parallel-connectivity) to make it faster. The op now runs in parallel (internally) via the DefaultChunkerOp, and instead of an if-thicket it has Delta Euler LUTs. As always, feel welcome to do whatever you wish with the code. I'd be interested to hear if you see any speed ups with real world data. A 200 x 200 x 200 cube saw ~ 400 ms speed gain.

**Comment by mdoube** [comment]
Here are a couple of test images, one is the result of Purify on emu.tif, the other is an XMT image of a TEM grid. Both complete in ≲1s on my 40-core workstation, using the BoneJ1 code. Please run your changes on it and report results and timings.

Results for each are:

Label | Euler ch. | Δ(χ) | Connectivity | Conn.D (mm^-3)
-------|-------------|-------|-----------------|-----------------------
binary_TEM_grid_aligned.tif | -1396 | -1396.000 | 1397.000 | 949.641
EmuPurifiedBoneJ1.tif | -30 | -30.125 | 31.125 | 0.630

[binary_TEM_grid_aligned.tif.zip](https://github.com/bonej-org/BoneJ2/files/3106141/binary_TEM_grid_aligned.tif.zip)
[EmuPurifiedBoneJ1.tif.zip](https://github.com/bonej-org/BoneJ2/files/3106142/EmuPurifiedBoneJ1.tif.zip)

**Comment by mdoube** [comment]
> I've been toying around with Connectivity [here](https://github.com/imagej/imagej-ops/commits/parallel-connectivity) to make it faster

I had a go with  your elegant LUT approach, but unfortunately it's quite a bit slower (~3×) than the 'if-thicket', I guess because `*` and array lookups are slower than `if(boolean)`. The bottleneck really seems to be the pixel lookup model, which using `Cursor` is about 2× slower than raw array access.
