### ISSUE TITLE
"Anisotropy could not be calculated - ellipsoid fitting failed" when no. Directions > ~800

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#109]
Ellipsoid fitting becomes unreliable at above around 800 directions. This compares rather unfavourably with BoneJ1 in which ellipsoids are fitted to 50,000 vectors by default. Notably, the default values on a fresh install of BoneJ2 is 2000 directions: a user's first experience of this plugin is likely to be "it didn't work".

**Comment by rimadoma** [comment]
This issue was most likely most likely fixed in PR #105. The problem was unrelated to the number of directions, rather we had incorrect criteria for checking whether a quadric equation could be an ellipsoid. The fix will be in the next release. If the problem persists in the next release, please reopen issue.
