### ISSUE TITLE
GitHub Services are being deprecated

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#114]
BoneJ2 relies on Travis via GitHub Services to do the continuous integration.

However, GitHub is deprecating Services. Travis recommend configuring a GitHub App instead:
https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/

**Comment by rimadoma** [comment]
Good catch, we'll have to keep an eye on how others adapt to this change and then follow suit. @ctrueden are you aware of this coming change?

**Comment by ctrueden** [comment]
Yes, I did install the Travis app into the imagej and scijava organizations awhile back. I did it while setting up a couple of new repositories to use travis-ci.com for the builds, since Travis is migrating/unifying open source builds over to travis-ci.com.

I am not too worried about proactively migrating everything; when the day comes where the legacy services completely break, I'm sure the next few days/weeks will be spent updating everything to use the Travis app instead, as time allows.
