### ISSUE TITLE
Show progress bar when wrappers are running

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/BoneJ2#115]
For each wrapper plug-in show the progress bar with `statusService.showProgress(completed, tasks);` in an appropriate manner. If the tasks are quick you could show progress with "1 / n subspaces processed". Otherwise you could show progress for each sub-space with "1 / n  processing completed" like in `Anisotropy`.

**Comment by ctrueden** [comment]
I think there is opportunity to improve the SciJava core here. The `StatusService` is a singleton progress bar and message, same as ImageJ1. There is now a `TaskService` that lets you spawn new tasks and keep track of their progress individually. What I have wanted for a long time is to tie in the tasks to the `StatusService`, so that you can do something like:
```java
Task task = taskService.createTask("Processing subspaces");
for (int i=0; i<subspaceCount; i++) {
  Task subtask = taskService.createTask("Processing subspace #" + i);
  task.addSubtask(subtask);
}
subspaceProcessor.launch(task); // or launch each subtasks, if multithreaded
statusService.setTask(task);
```

And then the status bar would reflect the status of the running tasks, including messages and progress, automatically. Some day, the ImageJ UI could even be improved to provide a dropdown details view similar to Eclipse with its subtasks, so that you can see everything currently going on.

The above is very rough off the top of my head—see the [`org.scijava.download` package](https://github.com/scijava/scijava-common/tree/scijava-common-2.75.0/src/main/java/org/scijava/download) where I really used the `TaskService` in practice.

The two things needed to make the above a reality:

1. Adding API to the `StatusService` to tie in with `Task`s.
2. Add API to the `Task` to allow for nested tasks.

What do you think @rimadoma? Does it make sense?

**Comment by rimadoma** [comment]
@ctrueden That sounds very handy, but frankly here I'm just trying to make the UI look like something is happening, so that the user doesn't BoneJ has frozen. In any case most of the action happens inside ops, so the bar wouldn't be updated that often even it worked in finer detail than per subspace. 

Is there a way to create a progress bar for a task with unknown number of iterations / time? Just something that darts back and forth while processing happens.

**Comment by ctrueden** [comment]
> Is there a way to create a progress bar for a task with unknown number of iterations / time?

No. ImageJ1 uses `java.awt.ProgressBar` which does not have an indeterminate mode, unlike Swing's `JProgressBar`. And we are stuck with the ImageJ1 UI.

**Comment by imagejan** [comment]
Maybe we can trick ImageJ1's ["Double Progress Bar"](https://imagej.net/macros/examples/DualProgressDemo.txt) into showing an indeterminate cycling dot?

**Comment by ctrueden** [comment]
@imagejan Wow, that's crazy!

Relatedly: digging in the source, I realize I made a mistake: `ij.gui.ProgressBar` extends `java.awt.Canvas`—there is no `java.awt.ProgressBar`. Sorry for steering people wrong there. I edited my message above to correct it.
