### ISSUE TITLE
Usage Reporter borks ImageJ's GUI when called for the first time from Slice Geometry

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#195]
stub issue, see 
https://forum.image.sc/t/problem-with-the-window-allow-usage-data-collection/31556
Précis: Usage Reporter blocks the ImageJ GUI, but only if Slice Geometry is the first BoneJ plugin you run.

**Comment by rimadoma** [comment]
This happens because `SliceGeometry` calls `Orienteer.getInstance()`, which causes `Orienteer` to call `UsageReporter.reportEvent(this).send();`. The premature, broken opt-in pop-up comes from `Orienteer`, not `SliceGeometry`! As soon as I commented out usage reporting in `Orienteer` the bug disappeared.

**Comment by mdoube** [comment]
Fixed by #206
